version: '3'

services:
  pokedex-db:
    container_name: pokedex-db
    image: mongo:5
    restart: always
    ports:
      - 27018:27017
    environment:
      MONGODB_DATABASE: nest-pokemon
    volumes:
      - ./mongo/pokedex:/data/db
